public class Salesforce {
    public void myFirstCode(){
        string city= 'Muğla';
        system.debug(city);

        string movie= 'Another Round';
        system.debug(movie);

        string season= 'Autumn';
        system.debug(season);
    }
    public void myFavorites(){
        integer myNmbr=6;
        system.debug(myNmbr);
        string city= 'Kitchener';
        system.debug(city);

        system.debug('My favorite number is ==> ' + myNmbr + ' and My Favorite city is ==> ' + city);

    }
}